begin;

create table public.plants (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  species text not null,
  description text not null,
  image_path text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.plant_facts (
  id uuid primary key default gen_random_uuid(),
  plant_id uuid not null references public.plants(id) on delete cascade,
  label text not null,
  value text not null,
  sort_order integer not null default 0,
  unique (plant_id, label)
);

create table public.plant_tags (
  id uuid primary key default gen_random_uuid(),
  plant_id uuid not null references public.plants(id) on delete cascade,
  label text not null,
  value text not null,
  icon_path text not null,
  sort_order integer not null default 0,
  unique (plant_id, label)
);

create table public.devices (
  id uuid primary key default gen_random_uuid(),
  device_id text not null unique,
  plant_id uuid not null references public.plants(id) on delete restrict,
  display_name text not null,
  installed_at timestamptz,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (plant_id, device_id)
);

create table public.sensor_readings (
  id bigint generated by default as identity primary key,
  plant_id uuid not null references public.plants(id) on delete restrict,
  device_id text not null,
  timestamp timestamptz not null,
  soil_moisture_raw integer not null,
  soil_moisture_percent numeric(5,2) not null
    constraint sensor_readings_soil_moisture_percent_check
    check (soil_moisture_percent >= 0 and soil_moisture_percent <= 100),
  temperature_c numeric(5,2) not null,
  humidity_percent numeric(5,2) not null
    constraint sensor_readings_humidity_percent_check
    check (humidity_percent >= 0 and humidity_percent <= 100),
  light_lux numeric(10,2) not null
    constraint sensor_readings_light_lux_check
    check (light_lux >= 0),
  sensor_status text not null
    constraint sensor_readings_sensor_status_check
    check (sensor_status in ('ok', 'warning', 'error', 'offline')),
  battery_or_power_status text,
  notes text,
  created_at timestamptz not null default now(),
  constraint sensor_readings_device_timestamp_key unique (device_id, timestamp),
  constraint sensor_readings_device_assignment_fkey
    foreign key (plant_id, device_id)
    references public.devices(plant_id, device_id)
    on delete restrict
);

create table public.plant_health_snapshots (
  id bigint generated by default as identity primary key,
  plant_id uuid not null references public.plants(id) on delete cascade,
  source_reading_id bigint references public.sensor_readings(id) on delete set null,
  plant_status text not null
    constraint plant_health_snapshots_status_check
    check (plant_status in ('Good', 'Needs water', 'Too dark', 'Too hot', 'Too dry', 'Sensor error')),
  plant_hp_percent integer not null
    constraint plant_health_snapshots_hp_check
    check (plant_hp_percent >= 0 and plant_hp_percent <= 100),
  mood_emoji text not null,
  mood_label text not null,
  mood_description text not null,
  generated_at timestamptz not null default now()
);

create table public.metric_thresholds (
  id uuid primary key default gen_random_uuid(),
  plant_id uuid not null references public.plants(id) on delete cascade,
  metric_key text not null
    constraint metric_thresholds_metric_key_check
    check (metric_key in ('soil_moisture', 'light', 'temperature', 'humidity')),
  display_title text not null,
  unit text not null,
  optimal_min numeric(10,2) not null,
  optimal_max numeric(10,2) not null,
  display_range text not null,
  sort_order integer not null default 0,
  unique (plant_id, metric_key)
);

create table public.care_guidelines (
  id uuid primary key default gen_random_uuid(),
  plant_id uuid not null references public.plants(id) on delete cascade,
  title text not null,
  body text not null,
  sort_order integer not null default 0,
  unique (plant_id, title)
);

create table public.care_advice (
  id uuid primary key default gen_random_uuid(),
  plant_id uuid not null references public.plants(id) on delete cascade,
  source_reading_id bigint references public.sensor_readings(id) on delete set null,
  title text not null,
  body text not null,
  action_label text,
  image_path text,
  status text not null default 'active'
    constraint care_advice_status_check
    check (status in ('active', 'completed', 'dismissed')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table public.ai_reports (
  id uuid primary key default gen_random_uuid(),
  plant_id uuid not null references public.plants(id) on delete cascade,
  source_reading_id bigint references public.sensor_readings(id) on delete set null,
  plant_message text not null,
  condition_summary text not null,
  near_future_prediction text not null,
  model_name text,
  prompt_version text,
  generated_at timestamptz not null default now()
);

create table public.activity_events (
  id uuid primary key default gen_random_uuid(),
  plant_id uuid not null references public.plants(id) on delete cascade,
  source_reading_id bigint references public.sensor_readings(id) on delete set null,
  event_type text not null,
  title text not null,
  description text,
  icon_path text,
  icon_background_color text,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index sensor_readings_plant_timestamp_idx
  on public.sensor_readings (plant_id, timestamp desc);

create index sensor_readings_device_timestamp_idx
  on public.sensor_readings (device_id, timestamp desc);

create index plant_health_snapshots_plant_generated_at_idx
  on public.plant_health_snapshots (plant_id, generated_at desc);

create index care_advice_plant_status_created_at_idx
  on public.care_advice (plant_id, status, created_at desc);

create index ai_reports_plant_generated_at_idx
  on public.ai_reports (plant_id, generated_at desc);

create index activity_events_plant_occurred_at_idx
  on public.activity_events (plant_id, occurred_at desc);

alter table public.plants enable row level security;
alter table public.plant_facts enable row level security;
alter table public.plant_tags enable row level security;
alter table public.devices enable row level security;
alter table public.sensor_readings enable row level security;
alter table public.plant_health_snapshots enable row level security;
alter table public.metric_thresholds enable row level security;
alter table public.care_guidelines enable row level security;
alter table public.care_advice enable row level security;
alter table public.ai_reports enable row level security;
alter table public.activity_events enable row level security;

create policy "Deny browser access"
  on public.plants for all to anon, authenticated
  using (false)
  with check (false);

create policy "Deny browser access"
  on public.plant_facts for all to anon, authenticated
  using (false)
  with check (false);

create policy "Deny browser access"
  on public.plant_tags for all to anon, authenticated
  using (false)
  with check (false);

create policy "Deny browser access"
  on public.devices for all to anon, authenticated
  using (false)
  with check (false);

create policy "Deny browser access"
  on public.sensor_readings for all to anon, authenticated
  using (false)
  with check (false);

create policy "Deny browser access"
  on public.plant_health_snapshots for all to anon, authenticated
  using (false)
  with check (false);

create policy "Deny browser access"
  on public.metric_thresholds for all to anon, authenticated
  using (false)
  with check (false);

create policy "Deny browser access"
  on public.care_guidelines for all to anon, authenticated
  using (false)
  with check (false);

create policy "Deny browser access"
  on public.care_advice for all to anon, authenticated
  using (false)
  with check (false);

create policy "Deny browser access"
  on public.ai_reports for all to anon, authenticated
  using (false)
  with check (false);

create policy "Deny browser access"
  on public.activity_events for all to anon, authenticated
  using (false)
  with check (false);

revoke all privileges on table
  public.plants,
  public.plant_facts,
  public.plant_tags,
  public.devices,
  public.sensor_readings,
  public.plant_health_snapshots,
  public.metric_thresholds,
  public.care_guidelines,
  public.care_advice,
  public.ai_reports,
  public.activity_events
from anon, authenticated, public;

grant select, insert, update, delete on table
  public.plants,
  public.plant_facts,
  public.plant_tags,
  public.devices,
  public.sensor_readings,
  public.plant_health_snapshots,
  public.metric_thresholds,
  public.care_guidelines,
  public.care_advice,
  public.ai_reports,
  public.activity_events
to service_role;

revoke all privileges on sequence
  public.sensor_readings_id_seq,
  public.plant_health_snapshots_id_seq
from anon, authenticated, public;

grant usage, select, update on sequence
  public.sensor_readings_id_seq,
  public.plant_health_snapshots_id_seq
to service_role;

revoke all privileges on all functions in schema public from anon, authenticated, public;
grant execute on all functions in schema public to service_role;

insert into public.plants (
  id,
  name,
  species,
  description,
  image_path,
  created_at,
  updated_at
)
values (
  '11111111-1111-4111-8111-111111111111',
  'Kono-Chan',
  'Golden Pothos',
  'Kono-Chan is a resilient Golden Pothos for the Konoha-gotchi prototype. The dashboard tracks moisture, light, temperature, and humidity so the plant care loop can move from mock data to real readings.',
  '/icon/mockplant.jpeg',
  '2026-06-16T09:00:00+09:00',
  '2026-06-16T09:00:00+09:00'
);

insert into public.plant_facts (plant_id, label, value, sort_order)
values
  ('11111111-1111-4111-8111-111111111111', 'Age', 'Prototype plant', 1),
  ('11111111-1111-4111-8111-111111111111', 'Origin', 'Solomon Islands', 2),
  ('11111111-1111-4111-8111-111111111111', 'Type', 'Tropical vine', 3);

insert into public.plant_tags (plant_id, label, value, icon_path, sort_order)
values
  ('11111111-1111-4111-8111-111111111111', 'Health', 'Good', '/icon/protect.png', 1),
  ('11111111-1111-4111-8111-111111111111', 'Soil moisture', 'Watchful', '/icon/leaves.png', 2),
  ('11111111-1111-4111-8111-111111111111', 'Light level', 'Bright indirect', '/icon/sun.png', 3);

insert into public.devices (
  id,
  device_id,
  plant_id,
  display_name,
  installed_at,
  is_active,
  created_at
)
values (
  '22222222-2222-4222-8222-222222222222',
  'konoha-esp32-01',
  '11111111-1111-4111-8111-111111111111',
  'Prototype ESP32 sensor node',
  '2026-06-16T09:00:00+09:00',
  true,
  '2026-06-16T09:00:00+09:00'
);

insert into public.sensor_readings (
  plant_id,
  device_id,
  timestamp,
  soil_moisture_raw,
  soil_moisture_percent,
  temperature_c,
  humidity_percent,
  light_lux,
  sensor_status,
  battery_or_power_status,
  notes
)
values
  ('11111111-1111-4111-8111-111111111111', 'konoha-esp32-01', '2026-06-16T06:00:00+09:00', 2320, 31, 21.8, 51.0, 120, 'ok', 'usb_power', 'Seeded dawn baseline reading.'),
  ('11111111-1111-4111-8111-111111111111', 'konoha-esp32-01', '2026-06-16T08:00:00+09:00', 2240, 35, 22.2, 49.5, 420, 'ok', 'usb_power', 'Seeded morning light increase.'),
  ('11111111-1111-4111-8111-111111111111', 'konoha-esp32-01', '2026-06-16T10:00:00+09:00', 2180, 38, 23.1, 48.9, 760, 'ok', 'usb_power', 'Seeded late morning reading.'),
  ('11111111-1111-4111-8111-111111111111', 'konoha-esp32-01', '2026-06-16T12:00:00+09:00', 2150, 34, 22.5, 48.2, 820, 'ok', 'usb_power', 'Seeded sample matching the Raspberry Pi ingestion contract.'),
  ('11111111-1111-4111-8111-111111111111', 'konoha-esp32-01', '2026-06-16T14:00:00+09:00', 2110, 33, 23.0, 47.8, 910, 'ok', 'usb_power', 'Seeded afternoon dashboard reading.'),
  ('11111111-1111-4111-8111-111111111111', 'konoha-esp32-01', '2026-06-16T16:00:00+09:00', 2080, 32, 22.7, 48.4, 640, 'ok', 'usb_power', 'Latest seeded reading for dashboard render.');

insert into public.metric_thresholds (
  plant_id,
  metric_key,
  display_title,
  unit,
  optimal_min,
  optimal_max,
  display_range,
  sort_order
)
values
  ('11111111-1111-4111-8111-111111111111', 'soil_moisture', 'Soil moisture', '%', 40, 60, '40% - 60%', 1),
  ('11111111-1111-4111-8111-111111111111', 'light', 'Light level', 'lux', 500, 1500, '500 - 1500 lux', 2),
  ('11111111-1111-4111-8111-111111111111', 'temperature', 'Temperature', 'C', 18, 28, '18C - 28C', 3),
  ('11111111-1111-4111-8111-111111111111', 'humidity', 'Air humidity', '%', 50, 75, '50% - 75%', 4);

insert into public.plant_health_snapshots (
  plant_id,
  source_reading_id,
  plant_status,
  plant_hp_percent,
  mood_emoji,
  mood_label,
  mood_description,
  generated_at
)
select
  '11111111-1111-4111-8111-111111111111',
  id,
  'Good',
  84,
  ':)',
  'Content',
  'Stable with slightly low soil moisture',
  '2026-06-16T16:02:00+09:00'
from public.sensor_readings
where device_id = 'konoha-esp32-01'
order by timestamp desc
limit 1;

insert into public.care_guidelines (plant_id, title, body, sort_order)
values
  ('11111111-1111-4111-8111-111111111111', 'Watering Routine', 'Water Kono-Chan when the top layer of soil feels dry. Golden Pothos prefers a short dry period between waterings.', 1),
  ('11111111-1111-4111-8111-111111111111', 'Light Requirements', 'Bright, indirect light is best. Avoid harsh direct afternoon sun and deep shade.', 2),
  ('11111111-1111-4111-8111-111111111111', 'Cleaning & Grooming', 'Wipe leaves gently to remove dust and trim yellowing leaves when needed.', 3),
  ('11111111-1111-4111-8111-111111111111', 'Feeding', 'Use a balanced liquid fertilizer during the growing season and pause heavy feeding during colder months.', 4);

insert into public.care_advice (
  plant_id,
  source_reading_id,
  title,
  body,
  action_label,
  image_path,
  status,
  created_at
)
select
  '11111111-1111-4111-8111-111111111111',
  id,
  'Care advice',
  'Soil moisture is trending low. Check the soil today and water Kono-Chan if the top layer feels dry.',
  'Mark as Watered',
  '/icon/water.jpeg',
  'active',
  '2026-06-16T16:05:00+09:00'
from public.sensor_readings
where device_id = 'konoha-esp32-01'
order by timestamp desc
limit 1;

insert into public.ai_reports (
  plant_id,
  source_reading_id,
  plant_message,
  condition_summary,
  near_future_prediction,
  model_name,
  prompt_version,
  generated_at
)
select
  '11111111-1111-4111-8111-111111111111',
  id,
  'I am feeling steady today.',
  'Moisture is slightly below the target range while light, temperature, and humidity are acceptable for the prototype demo.',
  'If moisture continues to drift down, Kono-Chan may need watering before the next class demo.',
  'seed-placeholder',
  'seed-v1',
  '2026-06-16T16:06:00+09:00'
from public.sensor_readings
where device_id = 'konoha-esp32-01'
order by timestamp desc
limit 1;

insert into public.activity_events (
  plant_id,
  source_reading_id,
  event_type,
  title,
  description,
  icon_path,
  icon_background_color,
  metadata,
  occurred_at
)
select
  '11111111-1111-4111-8111-111111111111',
  id,
  event_type,
  title,
  description,
  icon_path,
  icon_background_color,
  metadata,
  occurred_at
from (
  select
    (select id from public.sensor_readings where device_id = 'konoha-esp32-01' order by timestamp desc limit 1) as id,
    'sensor_reading' as event_type,
    'Moisture sensor reading logged' as title,
    'Latest prototype reading stored from the seeded Konoha device.' as description,
    '/icon/water-droplet.png' as icon_path,
    '#E3F2FD' as icon_background_color,
    '{"source":"seed"}'::jsonb as metadata,
    '2026-06-16T16:00:00+09:00'::timestamptz as occurred_at
  union all
  select
    (select id from public.sensor_readings where device_id = 'konoha-esp32-01' order by timestamp desc limit 1),
    'plant_status',
    'Plant status updated to Good',
    'Health snapshot generated from the latest seeded sensor reading.',
    '/icon/protect.png',
    '#E8F5E9',
    '{"source":"seed"}'::jsonb,
    '2026-06-16T16:02:00+09:00'::timestamptz
  union all
  select
    (select id from public.sensor_readings where device_id = 'konoha-esp32-01' order by timestamp desc limit 1),
    'care_advice',
    'Care advice refreshed',
    'Server-side placeholder advice created without calling Gemini.',
    '/icon/info.png',
    '#FFF3E0',
    '{"source":"seed"}'::jsonb,
    '2026-06-16T16:05:00+09:00'::timestamptz
  union all
  select
    (select id from public.sensor_readings where device_id = 'konoha-esp32-01' order by timestamp desc limit 1),
    'ai_report',
    'AI report placeholder seeded',
    'Placeholder report stored for the dashboard. Gemini integration remains out of scope.',
    '/icon/app.png',
    '#F3E5F5',
    '{"source":"seed","model":"placeholder"}'::jsonb,
    '2026-06-16T16:06:00+09:00'::timestamptz
  union all
  select
    (select id from public.sensor_readings where device_id = 'konoha-esp32-01' order by timestamp desc limit 1),
    'calibration',
    'Prototype device registered',
    'Device konoha-esp32-01 is active and assigned to Kono-Chan.',
    '/icon/sensor.png',
    '#E3F2FD',
    '{"source":"seed","device_id":"konoha-esp32-01"}'::jsonb,
    '2026-06-16T09:00:00+09:00'::timestamptz
) as seeded_events;

commit;
